/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.custom.Quantity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ContainerMetrics sets resource usage metrics of a container.
 */
@ApiModel(description = "ContainerMetrics sets resource usage metrics of a container.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-20T06:31:18.419Z[Etc/UTC]")
public class V1beta1ContainerMetrics {
  public static final String SERIALIZED_NAME_USAGE = "usage";
  @SerializedName(SERIALIZED_NAME_USAGE)
  private Map<String, Quantity> usage = new HashMap<String, Quantity>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public V1beta1ContainerMetrics usage(Map<String, Quantity> usage) {
    
    this.usage = usage;
    return this;
  }

  public V1beta1ContainerMetrics putUsageItem(String key, Quantity usageItem) {
    this.usage.put(key, usageItem);
    return this;
  }

   /**
   * The memory usage is the memory working set.
   * @return usage
  **/
  @ApiModelProperty(required = true, value = "The memory usage is the memory working set.")

  public Map<String, Quantity> getUsage() {
    return usage;
  }


  public void setUsage(Map<String, Quantity> usage) {
    this.usage = usage;
  }


  public V1beta1ContainerMetrics name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Container name corresponding to the one from pod.spec.containers.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Container name corresponding to the one from pod.spec.containers.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ContainerMetrics v1beta1ContainerMetrics = (V1beta1ContainerMetrics) o;
    return Objects.equals(this.usage, v1beta1ContainerMetrics.usage) &&
        Objects.equals(this.name, v1beta1ContainerMetrics.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usage, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ContainerMetrics {\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

