/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.models.V1InitializerV2;
import io.kubernetes.client.models.V1StatusV2;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Initializers tracks the progress of initialization.
 */
@ApiModel(description = "Initializers tracks the progress of initialization.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-20T06:31:18.419Z[Etc/UTC]")
public class V1InitializersV2 {
  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  private V1StatusV2 result;

  public static final String SERIALIZED_NAME_PENDING = "pending";
  @SerializedName(SERIALIZED_NAME_PENDING)
  private List<V1InitializerV2> pending = new ArrayList<V1InitializerV2>();


  public V1InitializersV2 result(V1StatusV2 result) {
    
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1StatusV2 getResult() {
    return result;
  }


  public void setResult(V1StatusV2 result) {
    this.result = result;
  }


  public V1InitializersV2 pending(List<V1InitializerV2> pending) {
    
    this.pending = pending;
    return this;
  }

  public V1InitializersV2 addPendingItem(V1InitializerV2 pendingItem) {
    this.pending.add(pendingItem);
    return this;
  }

   /**
   * Pending is a list of initializers that must execute in order before this object is visible. When the last pending initializer is removed, and no failing result is set, the initializers struct will be set to nil and the object is considered as initialized and visible to all clients.
   * @return pending
  **/
  @ApiModelProperty(required = true, value = "Pending is a list of initializers that must execute in order before this object is visible. When the last pending initializer is removed, and no failing result is set, the initializers struct will be set to nil and the object is considered as initialized and visible to all clients.")

  public List<V1InitializerV2> getPending() {
    return pending;
  }


  public void setPending(List<V1InitializerV2> pending) {
    this.pending = pending;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1InitializersV2 v1InitializersV2 = (V1InitializersV2) o;
    return Objects.equals(this.result, v1InitializersV2.result) &&
        Objects.equals(this.pending, v1InitializersV2.pending);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, pending);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1InitializersV2 {\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    pending: ").append(toIndentedString(pending)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

